### PR TITLE
Added "files" to package.json

### PR DESCRIPTION
**Pull request by bobzilladev**
This PR adds some more files to: https://github.com/ngrok/ngrok-nodejs/pull/100 from @neonexus

```
> npm pack
npm notice 
npm notice 📦  @ngrok/ngrok@0.9.0
npm notice === Tarball Contents === 
npm notice 2.5kB  CHANGELOG.md      
npm notice 3.3kB  CODE_OF_CONDUCT.md
npm notice 595B   CONTRIBUTING.md   
npm notice 11.4kB LICENSE-APACHE    
npm notice 1.1kB  LICENSE-MIT       
npm notice 13.7kB README.md         
npm notice 36.2kB index.d.ts        
npm notice 19.7kB index.js          
npm notice 2.0kB  package.json      
npm notice === Tarball Details === 
npm notice name:          @ngrok/ngrok                            
npm notice version:       0.9.0                                   
npm notice filename:      @ngrok/ngrok-0.9.0.tgz                  
npm notice package size:  22.2 kB                                 
npm notice unpacked size: 90.5 kB                                 
npm notice shasum:        ab9d4dc3e22316cd28155533def5f73050e819ce
npm notice integrity:     sha512-5Wn/wIlRTgPK6[...]JaCQYLcUO7C3Q==
npm notice total files:   9                                       
npm notice 
ngrok-ngrok-0.9.0.tgz
```

### CODE REVIEW

**Comment by neonexus** [comment]
The README and package.json are automatic, and don’t need to be included in the “files” listing.

**Comment by bobzilladev** [comment]
> The README and package.json are automatic, and don’t need to be included in the “files” listing.

Aye, just being explicit.

**Review by OfTheDelmer — APPROVED** [review]

**Comment by neonexus** [comment]
> > The README and package.json are automatic, and don’t need to be included in the “files” listing.
> 
> Aye, just being explicit.

@bobzilladev You know, I appreciate being explicit for a few reasons, I still have to ask: is adding the name of the file that is being read, to determine what files to include TRULY necessary? "Hey bro, I heard you like package.json..."

**Comment by bobzilladev** [comment]
I like that `files` has a list of everything that will be packaged 😄

**Comment by neonexus** [comment]
Fair enough.

On the plus side, this small addition dropped the package size from 1.03 MB in 149 files, down to 91KB and 9 files. MASSIVE improvement!

**Pull request merged**
